version: '3.8'

services:
  prover-node:
    image: aztecprotocol/aztec:0.87.8
    entrypoint: >
      sh -c 'node --no-warnings /usr/src/yarn-project/aztec/dest/bin/index.js start
      --prover-node --archiver --network alpha-testnet'
    depends_on:
      broker:
        condition: service_started
        required: true
    environment:
      PROVER_COORDINATION_NODE_URL: "http://111:8080"
      P2P_ANNOUNCE_ADDRESSES: "/ip4/111/tcp/40400"
      ETHEREUM_HOSTS: ""
      L1_CONSENSUS_HOST_URLS: ""
      PROVER_PUBLISHER_PRIVATE_KEY: "0x"
      PROVER_ENABLED: "true"
      P2P_ENABLED: "true"
      DATA_STORE_MAP_SIZE_KB: "134217728"
      LOG_LEVEL: "debug"
      PROVER_BROKER_HOST: "http://broker:8080"
    ports:
      - "8080:8080"
      - "40400:40400"
      - "40400:40400/udp"
    volumes:
      - /root/aztec-prover/node:/data

  broker:
    image: aztecprotocol/aztec:0.87.8
    entrypoint: >
      sh -c 'node --no-warnings /usr/src/yarn-project/aztec/dest/bin/index.js start
      --prover-broker --network alpha-testnet'
    environment:
      DATA_DIRECTORY: /data
      ETHEREUM_HOSTS: ""
      LOG_LEVEL: "debug"
    volumes:
      - /root/aztec-prover/broker:/data

  agent:
    image: aztecprotocol/aztec:0.87.8
    entrypoint: >
      sh -c 'node --no-warnings /usr/src/yarn-project/aztec/dest/bin/index.js start
      --prover-agent --network alpha-testnet'
    environment:
      PROVER_ID: "0x"
      PROVER_BROKER_HOST: "http://broker:8080"
      PROVER_AGENT_POLL_INTERVAL_MS: "10000"
    depends_on:
      - broker
    restart: unless-stopped
